users = [
    {
        "id": 1,
        "username": "alex_johnson",
        "email": "alex.johnson@example.com",
        "full_name": "Alex Johnson",
        "age": 28,
        "country": "USA",
        "is_active": True,
        "bio": "Software developer and tech enthusiast",
        "followers": 342,
        "posts": 47,
    },
    {
        "id": 2,
        "username": "sarah_williams",
        "email": "sarah.w@example.com",
        "full_name": "Sarah Williams",
        "age": 32,
        "country": "UK",
        "is_active": True,
        "bio": "Designer and creative thinker",
        "followers": 521,
        "posts": 89,
    },
    {
        "id": 3,
        "username": "michael_chen",
        "email": "mchen@example.com",
        "full_name": "Michael Chen",
        "age": 25,
        "country": "Canada",
        "is_active": False,
        "bio": "Data scientist exploring AI",
        "followers": 198,
        "posts": 23,
    },
    {
        "id": 4,
        "username": "emma_rodriguez",
        "email": "emma.r@example.com",
        "full_name": "Emma Rodriguez",
        "age": 29,
        "country": "Spain",
        "is_active": True,
        "bio": "Marketing professional and content creator",
        "followers": 687,
        "posts": 156,
    },
    {
        "id": 5,
        "username": "david_park",
        "email": "d.park@example.com",
        "full_name": "David Park",
        "age": 31,
        "country": "South Korea",
        "is_active": True,
        "bio": "Entrepreneur and startup founder",
        "followers": 412,
        "posts": 78,
    },
    {
        "id": 6,
        "username": "jessica_taylor",
        "email": "j.taylor@example.com",
        "full_name": "Jessica Taylor",
        "age": 26,
        "country": "Australia",
        "is_active": True,
        "bio": "Fitness coach and wellness advocate",
        "followers": 834,
        "posts": 203,
    },
    {
        "id": 7,
        "username": "marcus_smith",
        "email": "marcus.smith@example.com",
        "full_name": "Marcus Smith",
        "age": 35,
        "country": "USA",
        "is_active": False,
        "bio": "Finance analyst and investment advisor",
        "followers": 276,
        "posts": 45,
    },
    {
        "id": 8,
        "username": "olivia_brown",
        "email": "olivia.b@example.com",
        "full_name": "Olivia Brown",
        "age": 24,
        "country": "Germany",
        "is_active": True,
        "bio": "Photographer and visual storyteller",
        "followers": 1205,
        "posts": 287,
    },
    {
        "id": 9,
        "username": "james_wilson",
        "email": "j.wilson@example.com",
        "full_name": "James Wilson",
        "age": 38,
        "country": "USA",
        "is_active": True,
        "bio": "Business consultant and mentor",
        "followers": 543,
        "posts": 112,
    },
    {
        "id": 10,
        "username": "natasha_ivanova",
        "email": "n.ivanova@example.com",
        "full_name": "Natasha Ivanova",
        "age": 27,
        "country": "Russia",
        "is_active": True,
        "bio": "Musician and music producer",
        "followers": 762,
        "posts": 134,
    },
]
